apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: letsencrypt-certificate{{ if .Values.staging }}-stg{{ end }}
spec:
  secretName: letsencrypt-certificate{{ if .Values.staging }}-stg{{ end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt{{ if .Values.staging }}-stg{{ end }}
  dnsNames:
    - "*.{{ .Values.domainZone }}"
  acme:
    config:
    - dns01:
        provider: route53
      domains:
        - "*.{{ .Values.domainZone }}"
