version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: sanoma-smfdp/helm-charts
          command: .circleci/publish.sh
      - run:
          name: Verify
          command: |
            alias helm=/tmp/helm/bin/linux-amd64/helm
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              helm repo add smfdp https://sanoma-smfdp.github.io/helm-charts
              helm repo update
              helm repo list
              helm inspect smfdp/jenkins
            fi
