apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "authenticator.fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namspace: {{ .Release.Namespace }}
data:
  config.yaml: |
    clusterID: {{ .Values.clusterName }}
    server:
      mapRoles:
{{ toYaml .Values.mapRoles | indent 8 }}
      mapUsers:
{{ toYaml .Values.mapUsers | indent 8 }}
