# Default values for k8s-snapshots.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# https://github.com/miracle2k/k8s-snapshots/issues/54

replicaCount: 1
image:
  repository: elsdoerfer/k8s-snapshots
  tag: v2.0
  pullPolicy: IfNotPresent
rbac:
  create: true
useClaimName: true
runOnMasters: false
nameOverride: k8s-snapshots
