{{ range .Values.pvcList }}
{{ if (not .existingPersistentVolume) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: aws://{{ .ebsVolumeAZ | default "eu-west-1c" }}/{{ .ebsVolumeID }}
    fsType: ext4
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .size }}
  persistentVolumeReclaimPolicy: {{ .persistentVolumeReclaimPolicy | default "Delete" }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  {{ if .existingPersistentVolume }}
  volumeName: {{ .existingPersistentVolume }}
  {{ else }}
  volumeName: {{ .name }}
  {{ end }}
{{ end }}
