apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-jcasc
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namspace: {{ .Release.Namespace }}
data:
  jenkins.yaml: |
{{ toYaml .Values.configuration | indent 4 }}

    jobs:
{{ range .Values.jobGenerator }}
    - script: |
        def jobProperties = new groovy.json.JsonSlurper().parseText('{{ toJson .properties }}')
{{ $.Files.Get "jobdsl/job.groovy" | indent 8 }}
{{ end }}
