apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "jenkins.fullname" . }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      labels:
        app: {{ template "jenkins.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
    {{- with .Values.masterNodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.masterTolerations | indent 8 }}
      serviceAccountName: {{ template "jenkins.fullname" . }}
      initContainers:
      # Since we are configurting the jenkins master via configuration-as-code plugin
      # We only persist things that are generated during the lifetime of a Jenkins master
      # Everything else we clean up on every master restart
      - name: jenkins-home-sanitizer
        image: busybox
        restartPolicy:
        volumeMounts:
        - name: {{ template "jenkins.fullname" . }}-home
          mountPath: /var/jenkins_home
        command: ["sh", "-c"]
        args:
        - |
          find /var/jenkins_home \
            -not -name 'users' \
            -not -name 'jobs' \
            -not -name 'nodes' \
            -not -name 'scriptApproval.xml' \
            -not -name 'javaposse.jobdsl.plugin.ExecuteDslScripts.xml' \
            -delete
      containers:
      - name: jenkins
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ if .Values.privilegedContainer }}
        securityContext:
          privileged: true
        {{ end }}
        ports:
        - name: http
          containerPort: 8080
        - name: slavelistener
          containerPort: 50000
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "{{ .Values.javaOpts }}"
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs/..data/jenkins.yaml
        - name: SECRETS
          value: /secrets/jenkins
        volumeMounts:
        - name: jenkins-configuration-as-code
          mountPath: /var/jenkins_home/casc_configs
        - name: jenkins-secrets
          mountPath: /secrets/jenkins
          readOnly: true
        - name: jenkins-css
          mountPath: /var/jenkins_home/userContent/css
          readOnly: true
        - name: {{ template "jenkins.fullname" . }}-home
          mountPath: /var/jenkins_home
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: jenkins-configuration-as-code
        configMap:
          name: {{ template "jenkins.fullname" . }}-jcasc
      - name: jenkins-secrets
        secret:
          secretName: {{ .Values.secrets.name }}
      - name: jenkins-css
        configMap:
          name: {{ template "jenkins.fullname" . }}-css
      - name: {{ template "jenkins.fullname" . }}-home
        persistentVolumeClaim:
          {{ if not .Values.persistence.existingClaim }}
          claimName: {{ template "jenkins.fullname" . }}-home
          {{ else }}
          claimName: {{ .Values.persistence.existingClaim }}
          {{ end }}
