apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "jenkins.fullname" . }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      labels:
        app: {{ template "jenkins.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
    {{- with .Values.masterNodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.masterTolerations | indent 8 }}
      serviceAccountName: {{ template "jenkins.fullname" . }}
      containers:
      - name: jenkins
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["sh", "-c"]
        args:
        - /sbin/tini -- /usr/local/bin/jenkins.sh
        {{ if .Values.privilegedContainer }}
        securityContext:
          privileged: true
        {{ end }}
        ports:
        - name: http
          containerPort: 8080
        - name: slavelistener
          containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: "-Djava.util.logging.config.file=/var/jenkins_home/userContent/logging-conf/logging.properties {{ .Values.javaOpts }}"
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs/jenkins.yaml
        - name: SECRETS
          value: /secrets/jenkins
        volumeMounts:
        - name: jenkins-configuration-as-code
          mountPath: /var/jenkins_home/casc_configs
        - name: jenkins-secrets
          mountPath: /secrets/jenkins
          readOnly: true
        - name: jenkins-css
          mountPath: /var/jenkins_home/userContent/css
          readOnly: true
        - name: logging-properties
          mountPath: /var/jenkins_home/userContent/logging-conf
          readOnly: true
        - name: {{ template "jenkins.fullname" . }}-home
          mountPath: /var/jenkins_home
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
      volumes:
      - name: {{ template "jenkins.fullname" . }}-home
        persistentVolumeClaim:
          {{ if not .Values.persistence.jenkinsHome.existingClaim }}
          claimName: {{ template "jenkins.fullname" . }}-home
          {{ else }}
          claimName: {{ .Values.persistence.jenkinsHome.existingClaim }}
          {{ end }}
      - name: jenkins-configuration-as-code
        configMap:
          name: {{ template "jenkins.fullname" . }}-jcasc
      - name: jenkins-secrets
        secret:
          secretName: {{ .Values.secrets.name }}
      - name: jenkins-css
        configMap:
          name: {{ template "jenkins.fullname" . }}-css
      - name: logging-properties
        configMap:
          name: {{ template "jenkins.fullname" . }}-logging-properties
